package cad_prod;
// Generated Apr 21, 2020 10:08:24 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * Produtos generated by hbm2java
 */
@Entity
public class Produtos implements java.io.Serializable {

    @SequenceGenerator(name = "pk_sequence", sequenceName = "entity_id_seq", allocationSize = 1)
    private Integer id;
    private String codProd;
    private String descProd;
    private Integer qtdProd;
    private BigDecimal precoProd;

    public Produtos() {
    }

    public Produtos(int id) {
        this.id = id;
    }

    public Produtos(int id, String codProd, String descProd, Integer qtdProd, BigDecimal precoProd) {
        this.id = id;
        this.codProd = codProd;
        this.descProd = descProd;
        this.qtdProd = qtdProd;
        this.precoProd = precoProd;
    }

    @Column(name = "id", unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCodProd() {
        return this.codProd;
    }

    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }

    public String getDescProd() {
        return this.descProd;
    }

    public void setDescProd(String descProd) {
        this.descProd = descProd;
    }

    public Integer getQtdProd() {
        return this.qtdProd;
    }

    public void setQtdProd(Integer qtdProd) {
        this.qtdProd = qtdProd;
    }

    public BigDecimal getPrecoProd() {
        return this.precoProd;
    }

    public void setPrecoProd(BigDecimal precoProd) {
        this.precoProd = precoProd;
    }

}
